name: vietqr
description: A Package supporting content creation for QR money transfer 
version: 1.0.0

environment:
  sdk: '>=2.17.5 <3.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

flutter:
