name: vietqr
description: A Package supporting content creation for QR money transfer
version: 1.0.0

environment:
  sdk: ">=2.17.5 <4.0.0"

dev_dependencies:
  lint: ">=1.5.0 <3.0.0"
  test: ^1.16.0
